USE [ActivosFijos]
GO
/****** Object:  StoredProcedure [dbo].[usp_U_acfACTt_Actividad]    Script Date: 11/05/2017 10:06:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



-- Update one row based on the primary key(s)
------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 22/03/2017 10:50:32 
------------------------------------------------------------
CREATE PROCEDURE [dbo].[usp_U_acfGIS_UbicacionElectrica]
 @iUBEid int  
,@mUBEcodigogis bigint
,@mACFid int
,@mSELid bigint
,@mUBEset bigint
,@mUBEsetetq varchar
,@mUBEalimentador bigint
,@mUBEalimetiquetadoretq varchar
,@mUBEsed bigint
,@mUBEsedetq varchar
,@mUBcircuito bigint
,@mUBEcircuitoetq varchar
,@mUBEtipoPuntoi bigint
,@mUBEpuntoi bigint
,@mUBEpuntoietq varchar
,@mUBEtipoPuntof bigint
,@mUBEpuntof bigint
,@mUBEpuntofetq varchar
,@mUBEobra char
,@mKOSTL char
,@mZona char
,@mVNRid char
,@mCodNiff char
,@mValAct int
,@mVidUtilTrib int
,@mVidUtilFinan int
,@mUBEestado char
AS
-- updates a row in the table based on the primary key

UPDATE [dbo].[acfGIS_UbicacionElectrica]
SET
 UBEcodigogis = @mUBEcodigogis
,ACFid = @mACFid
,SELid = @mSELid
,UBEset = @mUBEset
,UBEsetetq = @mUBEsetetq
,UBEalimentador = @mUBEalimentador
,UBEalimetiquetadoretq = @mUBEalimetiquetadoretq
,UBEsed = @mUBEsed
,UBEsedetq = @mUBEsedetq
,UBcircuito = @mUBcircuito
,UBEcircuitoetq = @mUBEcircuitoetq
,UBEtipoPuntoi = @mUBEtipoPuntoi
,UBEpuntoi = @mUBEpuntoi
,UBEpuntoietq = @mUBEpuntoietq
,UBEtipoPuntof = @mUBEtipoPuntof
,UBEpuntof = @mUBEpuntof
,UBEpuntofetq = @mUBEpuntofetq
,UBEobra = @mUBEobra
,KOSTL = @mKOSTL
,Zona = @mZona
,VNRid = @mVNRid
,CodNiff = @mCodNiff
,ValAct = @mValAct
,VidUtilTrib = @mVidUtilTrib
,VidUtilFinan = @mVidUtilFinan
,UBEestado = @mUBEestado
WHERE 
UBEid = @iUBEid
SELECT 
@mUBEcodigogis = UBEcodigogis
,@mACFid = ACFid
,@mSELid = SELid
,@mUBEset = UBEset
,@mUBEsetetq = UBEsetetq
,@mUBEalimentador = UBEalimentador
,@mUBEalimetiquetadoretq = UBEalimetiquetadoretq
,@mUBEsed = UBEsed
,@mUBEsedetq = UBEsedetq
,@mUBcircuito = UBcircuito
,@mUBEcircuitoetq = UBEcircuitoetq
,@mUBEtipoPuntoi = UBEtipoPuntoi
,@mUBEpuntoi = UBEpuntoi
,@mUBEpuntoietq = UBEpuntoietq
,@mUBEtipoPuntof = UBEtipoPuntof
,@mUBEpuntof = UBEpuntof
,@mUBEpuntofetq = UBEpuntofetq
,@mUBEobra = UBEobra
,@mKOSTL = KOSTL
,@mZona = Zona
,@mVNRid = VNRid
,@mCodNiff = CodNiff
,@mValAct = ValAct
,@mVidUtilTrib = VidUtilTrib
,@mVidUtilFinan = VidUtilFinan
,@mUBEestado = UBEestado
FROM [dbo].[acfGIS_UbicacionElectrica]
WHERE 
UBEid = @iUBEid
