USE [ActivosFijos]
GO
DROP procedure [dbo].[usp_U_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_T_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_S_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_P_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_L_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_N_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_I_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_D_acfCMVp_Cabecera_Movimiento]
;
DROP PROCEDURE [dbo].[usp_B_acfCMVp_Cabecera_Movimiento]
;


-- Update one row based on the primary key(s)
------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 22/03/2017 10:50:32 
------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_U_acfCMVp_Cabecera_Movimiento]
    @iMVPid_proceso int  OUTPUT
	,@mMVPtipo char(1) OUTPUT
	-- ,@mMVPid_movimiento char(2) OUTPUT
	,@mMVPds_movimiento varchar(60) OUTPUT
	-- ,@mMVPid_motivo char(2) OUTPUT
	-- ,@mMVPds_motivo varchar(60) OUTPUT
	,@mMVPfecha_movimiento datetime OUTPUT
	-- ,@mORGid_empresa char(4) OUTPUT
	-- ,@mORGds_empresa varchar(60) OUTPUT
	,@mORGid_zona char(1) OUTPUT
	,@mORGds_zona varchar(20) OUTPUT
	-- ,@mORGid_crp char(4) OUTPUT
	,@mORGcrp char(13) OUTPUT
	,@mORGds_crp varchar(60) OUTPUT
	,@mORGid_ambiente char(4) OUTPUT
	,@mORGds_ambiente varchar(100) OUTPUT
	,@mORGid_persona char(10) OUTPUT
	,@mORGds_persona varchar(80) OUTPUT
	,@mORGid_usuario varchar(15) OUTPUT
	,@mORGds_usuario varchar(100) OUTPUT
	-- ,@mORGid_sistelec char(6) OUTPUT
	-- ,@mORGds_sistelec varchar(25) OUTPUT
	-- ,@mORGid_set char(15) OUTPUT
	-- ,@mORGds_set varchar(30) OUTPUT
	-- ,@mORGid_alimentador char(15) OUTPUT
	-- ,@mORGds_alimentador varchar(15) OUTPUT
	-- ,@mORGid_sed char(15) OUTPUT
	-- ,@mORGds_sed varchar(15) OUTPUT
	-- ,@mORGid_circuito char(15) OUTPUT
	-- ,@mORGds_circuito varchar(15) OUTPUT
	-- ,@mORGposte_inicio char(15) OUTPUT
	-- ,@mORGds_poste_inicio varchar(15) OUTPUT
	-- ,@mORGposte_fin char(15) OUTPUT
	-- ,@mORGds_poste_fin varchar(15) OUTPUT
	-- ,@mORGlinea_at char(15) OUTPUT
	-- ,@mORGpunto_inicio char(15) OUTPUT
	-- ,@mORGpunto_fin char(15) OUTPUT
	-- ,@mORGid_activopadre int OUTPUT
	-- ,@mORGds_activopadre varchar(200) OUTPUT
	-- ,@mDSTid_empresa char(4) OUTPUT
	-- ,@mDSTds_empresa varchar(60) OUTPUT
	,@mDSTid_zona char(1) OUTPUT
	,@mDSTds_zona varchar(20) OUTPUT
	-- ,@mDSTid_crp char(4) OUTPUT
	,@mDSTcrp char(13) OUTPUT
	,@mDSTds_crp varchar(60) OUTPUT
	,@mDSTid_ambiente char(4) OUTPUT
	,@mDSTds_ambiente varchar(100) OUTPUT
	,@mDSTid_persona char(10) OUTPUT
	,@mDSTds_persona varchar(80) OUTPUT
	,@mDSTid_usuario char(15) OUTPUT
	,@mDSTds_usuario varchar(100) OUTPUT
	-- ,@mDSTid_sistelec char(6) OUTPUT
	-- ,@mDSTds_sistelec varchar(25) OUTPUT
	-- ,@mDSTid_set char(5) OUTPUT
	-- ,@mDSTds_set varchar(30) OUTPUT
	-- ,@mDSTid_alimentador char(15) OUTPUT
	-- ,@mDSTds_alimentador varchar(15) OUTPUT
	-- ,@mDSTid_sed char(15) OUTPUT
	-- ,@mDSTds_sed varchar(15) OUTPUT
	-- ,@mDSTid_circuito char(15) OUTPUT
	-- ,@mDSTds_circuito varchar(15) OUTPUT
	-- ,@mDSTposte_inicio char(15) OUTPUT
	-- ,@mDSTds_poste_inicio varchar(15) OUTPUT
	-- ,@mDSTposte_fin char(15) OUTPUT
	-- ,@mDSTds_poste_fin varchar(15) OUTPUT
	-- ,@mDSTlinea_at char(15) OUTPUT
	-- ,@mDSTpunto_inicio char(15) OUTPUT
	-- ,@mDSTpunto_fin char(15) OUTPUT
	-- ,@mDSTid_activopadre int OUTPUT
	-- ,@mDSTds_activopadre varchar(200) OUTPUT
	-- ,@mMVPobservaciones varchar(240) OUTPUT
	-- ,@mMVPdefinitivo char(1) OUTPUT
	-- ,@mMVPfecha_fin datetime OUTPUT
	-- ,@mMVPusuario_sistemas char(10) OUTPUT
	-- ,@mMVPaprueba_sistemas bit OUTPUT
	-- ,@mMVPfecha_sistemas datetime OUTPUT
	-- ,@mMVPusuario_patrimonio char(10) OUTPUT
	-- ,@mMVPaprueba_patrimonio bit OUTPUT
	-- ,@mMVPfecha_patrimonio datetime OUTPUT
	-- ,@mMVPretorno char(1) OUTPUT
	-- ,@mMVPusuario_retorno char(10) OUTPUT
	-- ,@mMVPfecha_retorno char(10) OUTPUT
	-- ,@mMVPusuario_registro char(10) OUTPUT
	-- ,@mMVPfecha_registro datetime OUTPUT

AS
-- updates a row in the table based on the primary key

UPDATE [dbo].[acfCMVp_Cabecera_Movimiento]
SET
 [MVPtipo] = @mMVPtipo
-- ,[MVPid_movimiento] = @mMVPid_movimiento
 ,[MVPds_movimiento] = @mMVPds_movimiento
-- ,[MVPid_motivo] = @mMVPid_motivo
-- ,[MVPds_motivo] = @mMVPds_motivo
 ,[MVPfecha_movimiento] = @mMVPfecha_movimiento
-- ,[ORGid_empresa] = @mORGid_empresa
-- ,[ORGds_empresa] = @mORGds_empresa
 ,[ORGid_zona] = @mORGid_zona
 ,[ORGds_zona] = @mORGds_zona
-- ,[ORGid_crp] = @mORGid_crp
 ,[ORGcrp] = @mORGcrp
 ,[ORGds_crp] = @mORGds_crp
 ,[ORGid_ambiente] = @mORGid_ambiente
 ,[ORGds_ambiente] = @mORGds_ambiente
 ,[ORGid_persona] = @mORGid_persona
 ,[ORGds_persona] = @mORGds_persona
 ,[ORGid_usuario] = @mORGid_usuario
 ,[ORGds_usuario] = @mORGds_usuario
-- ,[ORGid_sistelec] = @mORGid_sistelec
-- ,[ORGds_sistelec] = @mORGds_sistelec
-- ,[ORGid_set] = @mORGid_set
-- ,[ORGds_set] = @mORGds_set
-- ,[ORGid_alimentador] = @mORGid_alimentador
-- ,[ORGds_alimentador] = @mORGds_alimentador
-- ,[ORGid_sed] = @mORGid_sed
-- ,[ORGds_sed] = @mORGds_sed
-- ,[ORGid_circuito] = @mORGid_circuito
-- ,[ORGds_circuito] = @mORGds_circuito
-- ,[ORGposte_inicio] = @mORGposte_inicio
-- ,[ORGds_poste_inicio] = @mORGds_poste_inicio
-- ,[ORGposte_fin] = @mORGposte_fin
-- ,[ORGds_poste_fin] = @mORGds_poste_fin
-- ,[ORGlinea_at] = @mORGlinea_at
-- ,[ORGpunto_inicio] = @mORGpunto_inicio
-- ,[ORGpunto_fin] = @mORGpunto_fin
-- ,[ORGid_activopadre] = @mORGid_activopadre
-- ,[ORGds_activopadre] = @mORGds_activopadre
-- ,[DSTid_empresa] = @mDSTid_empresa
-- ,[DSTds_empresa] = @mDSTds_empresa
 ,[DSTid_zona] = @mDSTid_zona
 ,[DSTds_zona] = @mDSTds_zona
-- ,[DSTid_crp] = @mDSTid_crp
 ,[DSTcrp] = @mDSTcrp
 ,[DSTds_crp] = @mDSTds_crp
 ,[DSTid_ambiente] = @mDSTid_ambiente
 ,[DSTds_ambiente] = @mDSTds_ambiente
 ,[DSTid_persona] = @mDSTid_persona
 ,[DSTds_persona] = @mDSTds_persona
 ,[DSTid_usuario] = @mDSTid_usuario
 ,[DSTds_usuario] = @mDSTds_usuario
-- ,[DSTid_sistelec] = @mDSTid_sistelec
-- ,[DSTds_sistelec] = @mDSTds_sistelec
-- ,[DSTid_set] = @mDSTid_set
-- ,[DSTds_set] = @mDSTds_set
-- ,[DSTid_alimentador] = @mDSTid_alimentador
-- ,[DSTds_alimentador] = @mDSTds_alimentador
-- ,[DSTid_sed] = @mDSTid_sed
-- ,[DSTds_sed] = @mDSTds_sed
-- ,[DSTid_circuito] = @mDSTid_circuito
-- ,[DSTds_circuito] = @mDSTds_circuito
-- ,[DSTposte_inicio] = @mDSTposte_inicio
-- ,[DSTds_poste_inicio] = @mDSTds_poste_inicio
-- ,[DSTposte_fin] = @mDSTposte_fin
-- ,[DSTds_poste_fin] = @mDSTds_poste_fin
-- ,[DSTlinea_at] = @mDSTlinea_at
-- ,[DSTpunto_inicio] = @mDSTpunto_inicio
-- ,[DSTpunto_fin] = @mDSTpunto_fin
-- ,[DSTid_activopadre] = @mDSTid_activopadre
-- ,[DSTds_activopadre] = @mDSTds_activopadre
-- ,[MVPobservaciones] = @mMVPobservaciones
-- ,[MVPdefinitivo] = @mMVPdefinitivo
-- ,[MVPfecha_fin] = @mMVPfecha_fin
-- ,[MVPusuario_sistemas] = @mMVPusuario_sistemas
-- ,[MVPaprueba_sistemas] = @mMVPaprueba_sistemas
-- ,[MVPfecha_sistemas] = @mMVPfecha_sistemas
-- ,[MVPusuario_patrimonio] = @mMVPusuario_patrimonio
-- ,[MVPaprueba_patrimonio] = @mMVPaprueba_patrimonio
-- ,[MVPfecha_patrimonio] = @mMVPfecha_patrimonio
-- ,[MVPretorno] = @mMVPretorno
-- ,[MVPusuario_retorno] = @mMVPusuario_retorno
-- ,[MVPfecha_retorno] = @mMVPfecha_retorno
-- ,[MVPusuario_registro] = @mMVPusuario_registro
-- ,[MVPfecha_registro] = @mMVPfecha_registro
WHERE 
[MVPid_proceso] = @iMVPid_proceso
SELECT 
 @iMVPid_proceso = [MVPid_proceso]
 ,@mMVPtipo = [MVPtipo]
-- ,@mMVPid_movimiento = [MVPid_movimiento]
 ,@mMVPds_movimiento = [MVPds_movimiento]
-- ,@mMVPid_motivo = [MVPid_motivo]
-- ,@mMVPds_motivo = [MVPds_motivo]
 ,@mMVPfecha_movimiento = [MVPfecha_movimiento]
-- ,@mORGid_empresa = [ORGid_empresa]
-- ,@mORGds_empresa = [ORGds_empresa]
 ,@mORGid_zona = [ORGid_zona]
 ,@mORGds_zona = [ORGds_zona]
-- ,@mORGid_crp = [ORGid_crp]
 ,@mORGcrp = [ORGcrp]
 ,@mORGds_crp = [ORGds_crp]
 ,@mORGid_ambiente = [ORGid_ambiente]
 ,@mORGds_ambiente = [ORGds_ambiente]
 ,@mORGid_persona = [ORGid_persona]
 ,@mORGds_persona = [ORGds_persona]
 ,@mORGid_usuario = [ORGid_usuario]
 ,@mORGds_usuario = [ORGds_usuario]
-- ,@mORGid_sistelec = [ORGid_sistelec]
-- ,@mORGds_sistelec = [ORGds_sistelec]
-- ,@mORGid_set = [ORGid_set]
-- ,@mORGds_set = [ORGds_set]
-- ,@mORGid_alimentador = [ORGid_alimentador]
-- ,@mORGds_alimentador = [ORGds_alimentador]
-- ,@mORGid_sed = [ORGid_sed]
-- ,@mORGds_sed = [ORGds_sed]
-- ,@mORGid_circuito = [ORGid_circuito]
-- ,@mORGds_circuito = [ORGds_circuito]
-- ,@mORGposte_inicio = [ORGposte_inicio]
-- ,@mORGds_poste_inicio = [ORGds_poste_inicio]
-- ,@mORGposte_fin = [ORGposte_fin]
-- ,@mORGds_poste_fin = [ORGds_poste_fin]
-- ,@mORGlinea_at = [ORGlinea_at]
-- ,@mORGpunto_inicio = [ORGpunto_inicio]
-- ,@mORGpunto_fin = [ORGpunto_fin]
-- ,@mORGid_activopadre = [ORGid_activopadre]
-- ,@mORGds_activopadre = [ORGds_activopadre]
-- ,@mDSTid_empresa = [DSTid_empresa]
-- ,@mDSTds_empresa = [DSTds_empresa]
 ,@mDSTid_zona = [DSTid_zona]
 ,@mDSTds_zona = [DSTds_zona]
-- ,@mDSTid_crp = [DSTid_crp]
 ,@mDSTcrp = [DSTcrp]
 ,@mDSTds_crp = [DSTds_crp]
 ,@mDSTid_ambiente = [DSTid_ambiente]
 ,@mDSTds_ambiente = [DSTds_ambiente]
 ,@mDSTid_persona = [DSTid_persona]
 ,@mDSTds_persona = [DSTds_persona]
 ,@mDSTid_usuario = [DSTid_usuario]
 ,@mDSTds_usuario = [DSTds_usuario]
-- ,@mDSTid_sistelec = [DSTid_sistelec]
-- ,@mDSTds_sistelec = [DSTds_sistelec]
-- ,@mDSTid_set = [DSTid_set]
-- ,@mDSTds_set = [DSTds_set]
-- ,@mDSTid_alimentador = [DSTid_alimentador]
-- ,@mDSTds_alimentador = [DSTds_alimentador]
-- ,@mDSTid_sed = [DSTid_sed]
-- ,@mDSTds_sed = [DSTds_sed]
-- ,@mDSTid_circuito = [DSTid_circuito]
-- ,@mDSTds_circuito = [DSTds_circuito]
-- ,@mDSTposte_inicio = [DSTposte_inicio]
-- ,@mDSTds_poste_inicio = [DSTds_poste_inicio]
-- ,@mDSTposte_fin = [DSTposte_fin]
-- ,@mDSTds_poste_fin = [DSTds_poste_fin]
-- ,@mDSTlinea_at = [DSTlinea_at]
-- ,@mDSTpunto_inicio = [DSTpunto_inicio]
-- ,@mDSTpunto_fin = [DSTpunto_fin]
-- ,@mDSTid_activopadre = [DSTid_activopadre]
-- ,@mDSTds_activopadre = [DSTds_activopadre]
-- ,@mMVPobservaciones = [MVPobservaciones]
-- ,@mMVPdefinitivo = [MVPdefinitivo]
-- ,@mMVPfecha_fin = [MVPfecha_fin]
-- ,@mMVPusuario_sistemas = [MVPusuario_sistemas]
-- ,@mMVPaprueba_sistemas = [MVPaprueba_sistemas]
-- ,@mMVPfecha_sistemas = [MVPfecha_sistemas]
-- ,@mMVPusuario_patrimonio = [MVPusuario_patrimonio]
-- ,@mMVPaprueba_patrimonio = [MVPaprueba_patrimonio]
-- ,@mMVPfecha_patrimonio = [MVPfecha_patrimonio]
-- ,@mMVPretorno = [MVPretorno]
-- ,@mMVPusuario_retorno = [MVPusuario_retorno]
-- ,@mMVPfecha_retorno = [MVPfecha_retorno]
-- ,@mMVPusuario_registro = [MVPusuario_registro]
-- ,@mMVPfecha_registro = [MVPfecha_registro]
FROM [dbo].[acfCMVp_Cabecera_Movimiento]
WHERE 
[MVPid_proceso] = @iMVPid_proceso
END











CREATE PROCEDURE [dbo].[usp_T_acfCMVp_Cabecera_Movimiento]
AS
BEGIN
SELECT TOP 1 
 MVPid_proceso,
 MVPtipo,
-- MVPid_movimiento,
 MVPds_movimiento,
-- MVPid_motivo,
-- MVPds_motivo,
 MVPfecha_movimiento,
-- ORGid_empresa,
-- ORGds_empresa,
 ORGid_zona,
 ORGds_zona,
-- ORGid_crp,
 ORGcrp,
 ORGds_crp,
 ORGid_ambiente,
 ORGds_ambiente,
 ORGid_persona,
 ORGds_persona,
 ORGid_usuario,
 ORGds_usuario,
-- ORGid_sistelec,
-- ORGds_sistelec,
-- ORGid_set,
-- ORGds_set,
-- ORGid_alimentador,
-- ORGds_alimentador,
-- ORGid_sed,
-- ORGds_sed,
-- ORGid_circuito,
-- ORGds_circuito,
-- ORGposte_inicio,
-- ORGds_poste_inicio,
-- ORGposte_fin,
-- ORGds_poste_fin,
-- ORGlinea_at,
-- ORGpunto_inicio,
-- ORGpunto_fin,
-- ORGid_activopadre,
-- ORGds_activopadre,
-- DSTid_empresa,
-- DSTds_empresa,
 DSTid_zona,
 DSTds_zona,
-- DSTid_crp,
 DSTcrp,
 DSTds_crp,
 DSTid_ambiente,
 DSTds_ambiente,
 DSTid_persona,
 DSTds_persona,
 DSTid_usuario,
 DSTds_usuario
-- DSTid_sistelec,
-- DSTds_sistelec,
-- DSTid_set,
-- DSTds_set,
-- DSTid_alimentador,
-- DSTds_alimentador,
-- DSTid_sed,
-- DSTds_sed,
-- DSTid_circuito,
-- DSTds_circuito,
-- DSTposte_inicio,
-- DSTds_poste_inicio,
-- DSTposte_fin,
-- DSTds_poste_fin,
-- DSTlinea_at,
-- DSTpunto_inicio,
-- DSTpunto_fin,
-- DSTid_activopadre,
-- DSTds_activopadre,
-- MVPobservaciones,
-- MVPdefinitivo,
-- MVPfecha_fin,
-- MVPusuario_sistemas,
-- MVPaprueba_sistemas,
-- MVPfecha_sistemas,
-- MVPusuario_patrimonio,
-- MVPaprueba_patrimonio,
-- MVPfecha_patrimonio,
-- MVPretorno,
-- MVPusuario_retorno,
-- MVPfecha_retorno,
-- MVPusuario_registro,
-- MVPfecha_registro
FROM acfCMVp_Cabecera_Movimiento
ORDER BY  MVPid_proceso ASC
END















-- Select All rows
------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 22/03/2017 10:50:32 
------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_S_acfCMVp_Cabecera_Movimiento]
AS
-- selects all rows from the table
SELECT 
 [MVPid_proceso]
 ,[MVPtipo]
-- ,[MVPid_movimiento]
 ,[MVPds_movimiento]
-- ,[MVPid_motivo]
-- ,[MVPds_motivo]
 ,[MVPfecha_movimiento]
-- ,[ORGid_empresa]
-- ,[ORGds_empresa]
 ,[ORGid_zona]
 ,[ORGds_zona]
-- ,[ORGid_crp]
 ,[ORGcrp]
 ,[ORGds_crp]
 ,[ORGid_ambiente]
 ,[ORGds_ambiente]
 ,[ORGid_persona]
 ,[ORGds_persona]
 ,[ORGid_usuario]
 ,[ORGds_usuario]
-- ,[ORGid_sistelec]
-- ,[ORGds_sistelec]
-- ,[ORGid_set]
-- ,[ORGds_set]
-- ,[ORGid_alimentador]
-- ,[ORGds_alimentador]
-- ,[ORGid_sed]
-- ,[ORGds_sed]
-- ,[ORGid_circuito]
-- ,[ORGds_circuito]
-- ,[ORGposte_inicio]
-- ,[ORGds_poste_inicio]
-- ,[ORGposte_fin]
-- ,[ORGds_poste_fin]
-- ,[ORGlinea_at]
-- ,[ORGpunto_inicio]
-- ,[ORGpunto_fin]
-- ,[ORGid_activopadre]
-- ,[ORGds_activopadre]
-- ,[DSTid_empresa]
-- ,[DSTds_empresa]
 ,[DSTid_zona]
 ,[DSTds_zona]
-- ,[DSTid_crp]
 ,[DSTcrp]
 ,[DSTds_crp]
 ,[DSTid_ambiente]
 ,[DSTds_ambiente]
 ,[DSTid_persona]
 ,[DSTds_persona]
 ,[DSTid_usuario]
 ,[DSTds_usuario]
-- ,[DSTid_sistelec]
-- ,[DSTds_sistelec]
-- ,[DSTid_set]
-- ,[DSTds_set]
-- ,[DSTid_alimentador]
-- ,[DSTds_alimentador]
-- ,[DSTid_sed]
-- ,[DSTds_sed]
-- ,[DSTid_circuito]
-- ,[DSTds_circuito]
-- ,[DSTposte_inicio]
-- ,[DSTds_poste_inicio]
-- ,[DSTposte_fin]
-- ,[DSTds_poste_fin]
-- ,[DSTlinea_at]
-- ,[DSTpunto_inicio]
-- ,[DSTpunto_fin]
-- ,[DSTid_activopadre]
-- ,[DSTds_activopadre]
-- ,[MVPobservaciones]
-- ,[MVPdefinitivo]
-- ,[MVPfecha_fin]
-- ,[MVPusuario_sistemas]
-- ,[MVPaprueba_sistemas]
-- ,[MVPfecha_sistemas]
-- ,[MVPusuario_patrimonio]
-- ,[MVPaprueba_patrimonio]
-- ,[MVPfecha_patrimonio]
-- ,[MVPretorno]
-- ,[MVPusuario_retorno]
-- ,[MVPfecha_retorno]
-- ,[MVPusuario_registro]
-- ,[MVPfecha_registro]
FROM [dbo].[acfCMVp_Cabecera_Movimiento]
END


















CREATE PROCEDURE [dbo].[usp_P_acfCMVp_Cabecera_Movimiento]
@iMVPid_proceso AS INT
AS
IF(SELECT COUNT(MVPid_proceso) FROM acfCMVp_Cabecera_Movimiento WHERE MVPid_proceso < @iMVPid_proceso) > 0
BEGIN
SELECT TOP 1 
 MVPid_proceso,
 MVPtipo,
-- MVPid_movimiento,
 MVPds_movimiento,
-- MVPid_motivo,
-- MVPds_motivo,
 MVPfecha_movimiento,
-- ORGid_empresa,
-- ORGds_empresa,
 ORGid_zona,
 ORGds_zona,
-- ORGid_crp,
 ORGcrp,
 ORGds_crp,
 ORGid_ambiente,
 ORGds_ambiente,
 ORGid_persona,
 ORGds_persona,
 ORGid_usuario,
 ORGds_usuario,
-- ORGid_sistelec,
-- ORGds_sistelec,
-- ORGid_set,
-- ORGds_set,
-- ORGid_alimentador,
-- ORGds_alimentador,
-- ORGid_sed,
-- ORGds_sed,
-- ORGid_circuito,
-- ORGds_circuito,
-- ORGposte_inicio,
-- ORGds_poste_inicio,
-- ORGposte_fin,
-- ORGds_poste_fin,
-- ORGlinea_at,
-- ORGpunto_inicio,
-- ORGpunto_fin,
-- ORGid_activopadre,
-- ORGds_activopadre,
-- DSTid_empresa,
-- DSTds_empresa,
 DSTid_zona,
 DSTds_zona,
-- DSTid_crp,
 DSTcrp,
 DSTds_crp,
 DSTid_ambiente,
 DSTds_ambiente,
 DSTid_persona,
 DSTds_persona,
 DSTid_usuario,
 DSTds_usuario
-- DSTid_sistelec,
-- DSTds_sistelec,
-- DSTid_set,
-- DSTds_set,
-- DSTid_alimentador,
-- DSTds_alimentador,
-- DSTid_sed,
-- DSTds_sed,
-- DSTid_circuito,
-- DSTds_circuito,
-- DSTposte_inicio,
-- DSTds_poste_inicio,
-- DSTposte_fin,
-- DSTds_poste_fin,
-- DSTlinea_at,
-- DSTpunto_inicio,
-- DSTpunto_fin,
-- DSTid_activopadre,
-- DSTds_activopadre,
-- MVPobservaciones,
-- MVPdefinitivo,
-- MVPfecha_fin,
-- MVPusuario_sistemas,
-- MVPaprueba_sistemas,
-- MVPfecha_sistemas,
-- MVPusuario_patrimonio,
-- MVPaprueba_patrimonio,
-- MVPfecha_patrimonio,
-- MVPretorno,
-- MVPusuario_retorno,
-- MVPfecha_retorno,
-- MVPusuario_registro,
-- MVPfecha_registro
FROM acfCMVp_Cabecera_Movimiento
WHERE MVPid_proceso < @iMVPid_proceso
ORDER BY  MVPid_proceso DESC
END
ELSE
BEGIN
SELECT TOP 1 
 MVPid_proceso,
 MVPtipo,
-- MVPid_movimiento,
 MVPds_movimiento,
-- MVPid_motivo,
-- MVPds_motivo,
 MVPfecha_movimiento,
-- ORGid_empresa,
-- ORGds_empresa,
 ORGid_zona,
 ORGds_zona,
-- ORGid_crp,
 ORGcrp,
 ORGds_crp,
 ORGid_ambiente,
 ORGds_ambiente,
 ORGid_persona,
 ORGds_persona,
 ORGid_usuario,
 ORGds_usuario,
-- ORGid_sistelec,
-- ORGds_sistelec,
-- ORGid_set,
-- ORGds_set,
-- ORGid_alimentador,
-- ORGds_alimentador,
-- ORGid_sed,
-- ORGds_sed,
-- ORGid_circuito,
-- ORGds_circuito,
-- ORGposte_inicio,
-- ORGds_poste_inicio,
-- ORGposte_fin,
-- ORGds_poste_fin,
-- ORGlinea_at,
-- ORGpunto_inicio,
-- ORGpunto_fin,
-- ORGid_activopadre,
-- ORGds_activopadre,
-- DSTid_empresa,
-- DSTds_empresa,
 DSTid_zona,
 DSTds_zona,
-- DSTid_crp,
 DSTcrp,
 DSTds_crp,
 DSTid_ambiente,
 DSTds_ambiente,
 DSTid_persona,
 DSTds_persona,
 DSTid_usuario,
 DSTds_usuario
-- DSTid_sistelec,
-- DSTds_sistelec,
-- DSTid_set,
-- DSTds_set,
-- DSTid_alimentador,
-- DSTds_alimentador,
-- DSTid_sed,
-- DSTds_sed,
-- DSTid_circuito,
-- DSTds_circuito,
-- DSTposte_inicio,
-- DSTds_poste_inicio,
-- DSTposte_fin,
-- DSTds_poste_fin,
-- DSTlinea_at,
-- DSTpunto_inicio,
-- DSTpunto_fin,
-- DSTid_activopadre,
-- DSTds_activopadre,
-- MVPobservaciones,
-- MVPdefinitivo,
-- MVPfecha_fin,
-- MVPusuario_sistemas,
-- MVPaprueba_sistemas,
-- MVPfecha_sistemas,
-- MVPusuario_patrimonio,
-- MVPaprueba_patrimonio,
-- MVPfecha_patrimonio,
-- MVPretorno,
-- MVPusuario_retorno,
-- MVPfecha_retorno,
-- MVPusuario_registro,
-- MVPfecha_registro
FROM acfCMVp_Cabecera_Movimiento
ORDER BY  MVPid_proceso ASC
END
















CREATE PROCEDURE [dbo].[usp_L_acfCMVp_Cabecera_Movimiento]
AS
BEGIN
SELECT TOP 1 
 MVPid_proceso,
 MVPtipo,
-- MVPid_movimiento,
 MVPds_movimiento,
-- MVPid_motivo,
-- MVPds_motivo,
 MVPfecha_movimiento,
-- ORGid_empresa,
-- ORGds_empresa,
 ORGid_zona,
 ORGds_zona,
-- ORGid_crp,
 ORGcrp,
 ORGds_crp,
 ORGid_ambiente,
 ORGds_ambiente,
 ORGid_persona,
 ORGds_persona,
 ORGid_usuario,
 ORGds_usuario,
-- ORGid_sistelec,
-- ORGds_sistelec,
-- ORGid_set,
-- ORGds_set,
-- ORGid_alimentador,
-- ORGds_alimentador,
-- ORGid_sed,
-- ORGds_sed,
-- ORGid_circuito,
-- ORGds_circuito,
-- ORGposte_inicio,
-- ORGds_poste_inicio,
-- ORGposte_fin,
-- ORGds_poste_fin,
-- ORGlinea_at,
-- ORGpunto_inicio,
-- ORGpunto_fin,
-- ORGid_activopadre,
-- ORGds_activopadre,
-- DSTid_empresa,
-- DSTds_empresa,
 DSTid_zona,
 DSTds_zona,
-- DSTid_crp,
 DSTcrp,
 DSTds_crp,
 DSTid_ambiente,
 DSTds_ambiente,
 DSTid_persona,
 DSTds_persona,
 DSTid_usuario,
 DSTds_usuario
-- DSTid_sistelec,
-- DSTds_sistelec,
-- DSTid_set,
-- DSTds_set,
-- DSTid_alimentador,
-- DSTds_alimentador,
-- DSTid_sed,
-- DSTds_sed,
-- DSTid_circuito,
-- DSTds_circuito,
-- DSTposte_inicio,
-- DSTds_poste_inicio,
-- DSTposte_fin,
-- DSTds_poste_fin,
-- DSTlinea_at,
-- DSTpunto_inicio,
-- DSTpunto_fin,
-- DSTid_activopadre,
-- DSTds_activopadre,
-- MVPobservaciones,
-- MVPdefinitivo,
-- MVPfecha_fin,
-- MVPusuario_sistemas,
-- MVPaprueba_sistemas,
-- MVPfecha_sistemas,
-- MVPusuario_patrimonio,
-- MVPaprueba_patrimonio,
-- MVPfecha_patrimonio,
-- MVPretorno,
-- MVPusuario_retorno,
-- MVPfecha_retorno,
-- MVPusuario_registro,
-- MVPfecha_registro
FROM acfCMVp_Cabecera_Movimiento
ORDER BY  MVPid_proceso DESC
END
























CREATE PROCEDURE [dbo].[usp_N_acfCMVp_Cabecera_Movimiento]
@iMVPid_proceso AS INT
AS
IF(SELECT COUNT(MVPid_proceso) FROM acfCMVp_Cabecera_Movimiento WHERE MVPid_proceso > @iMVPid_proceso) > 0
BEGIN
SELECT TOP 1 
 MVPid_proceso,
 MVPtipo,
-- MVPid_movimiento,
 MVPds_movimiento,
-- MVPid_motivo,
-- MVPds_motivo,
 MVPfecha_movimiento,
-- ORGid_empresa,
-- ORGds_empresa,
 ORGid_zona,
 ORGds_zona,
-- ORGid_crp,
 ORGcrp,
 ORGds_crp,
 ORGid_ambiente,
 ORGds_ambiente,
 ORGid_persona,
 ORGds_persona,
 ORGid_usuario,
 ORGds_usuario,
-- ORGid_sistelec,
-- ORGds_sistelec,
-- ORGid_set,
-- ORGds_set,
-- ORGid_alimentador,
-- ORGds_alimentador,
-- ORGid_sed,
-- ORGds_sed,
-- ORGid_circuito,
-- ORGds_circuito,
-- ORGposte_inicio,
-- ORGds_poste_inicio,
-- ORGposte_fin,
-- ORGds_poste_fin,
-- ORGlinea_at,
-- ORGpunto_inicio,
-- ORGpunto_fin,
-- ORGid_activopadre,
-- ORGds_activopadre,
-- DSTid_empresa,
-- DSTds_empresa,
 DSTid_zona,
 DSTds_zona,
-- DSTid_crp,
 DSTcrp,
 DSTds_crp,
 DSTid_ambiente,
 DSTds_ambiente,
 DSTid_persona,
 DSTds_persona,
 DSTid_usuario,
 DSTds_usuario
-- DSTid_sistelec,
-- DSTds_sistelec,
-- DSTid_set,
-- DSTds_set,
-- DSTid_alimentador,
-- DSTds_alimentador,
-- DSTid_sed,
-- DSTds_sed,
-- DSTid_circuito,
-- DSTds_circuito,
-- DSTposte_inicio,
-- DSTds_poste_inicio,
-- DSTposte_fin,
-- DSTds_poste_fin,
-- DSTlinea_at,
-- DSTpunto_inicio,
-- DSTpunto_fin,
-- DSTid_activopadre,
-- DSTds_activopadre,
-- MVPobservaciones,
-- MVPdefinitivo,
-- MVPfecha_fin,
-- MVPusuario_sistemas,
-- MVPaprueba_sistemas,
-- MVPfecha_sistemas,
-- MVPusuario_patrimonio,
-- MVPaprueba_patrimonio,
-- MVPfecha_patrimonio,
-- MVPretorno,
-- MVPusuario_retorno,
-- MVPfecha_retorno,
-- MVPusuario_registro,
-- MVPfecha_registro
FROM acfCMVp_Cabecera_Movimiento
WHERE MVPid_proceso > @iMVPid_proceso
ORDER BY  MVPid_proceso ASC
END
ELSE
BEGIN
SELECT TOP 1 
 MVPid_proceso,
 MVPtipo,
-- MVPid_movimiento,
 MVPds_movimiento,
-- MVPid_motivo,
-- MVPds_motivo,
 MVPfecha_movimiento,
-- ORGid_empresa,
-- ORGds_empresa,
 ORGid_zona,
 ORGds_zona,
-- ORGid_crp,
 ORGcrp,
 ORGds_crp,
 ORGid_ambiente,
 ORGds_ambiente,
 ORGid_persona,
 ORGds_persona,
 ORGid_usuario,
 ORGds_usuario,
-- ORGid_sistelec,
-- ORGds_sistelec,
-- ORGid_set,
-- ORGds_set,
-- ORGid_alimentador,
-- ORGds_alimentador,
-- ORGid_sed,
-- ORGds_sed,
-- ORGid_circuito,
-- ORGds_circuito,
-- ORGposte_inicio,
-- ORGds_poste_inicio,
-- ORGposte_fin,
-- ORGds_poste_fin,
-- ORGlinea_at,
-- ORGpunto_inicio,
-- ORGpunto_fin,
-- ORGid_activopadre,
-- ORGds_activopadre,
-- DSTid_empresa,
-- DSTds_empresa,
 DSTid_zona,
 DSTds_zona,
-- DSTid_crp,
 DSTcrp,
 DSTds_crp,
 DSTid_ambiente,
 DSTds_ambiente,
 DSTid_persona,
 DSTds_persona,
 DSTid_usuario,
 DSTds_usuario
-- DSTid_sistelec,
-- DSTds_sistelec,
-- DSTid_set,
-- DSTds_set,
-- DSTid_alimentador,
-- DSTds_alimentador,
-- DSTid_sed,
-- DSTds_sed,
-- DSTid_circuito,
-- DSTds_circuito,
-- DSTposte_inicio,
-- DSTds_poste_inicio,
-- DSTposte_fin,
-- DSTds_poste_fin,
-- DSTlinea_at,
-- DSTpunto_inicio,
-- DSTpunto_fin,
-- DSTid_activopadre,
-- DSTds_activopadre,
-- MVPobservaciones,
-- MVPdefinitivo,
-- MVPfecha_fin,
-- MVPusuario_sistemas,
-- MVPaprueba_sistemas,
-- MVPfecha_sistemas,
-- MVPusuario_patrimonio,
-- MVPaprueba_patrimonio,
-- MVPfecha_patrimonio,
-- MVPretorno,
-- MVPusuario_retorno,
-- MVPfecha_retorno,
-- MVPusuario_registro,
-- MVPfecha_registro
FROM acfCMVp_Cabecera_Movimiento
ORDER BY  MVPid_proceso DESC
END














-- Insert a new row
------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 22/03/2017 10:50:32 
------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_I_acfCMVp_Cabecera_Movimiento]
     @iMVPid_proceso int  OUTPUT
	,@mMVPtipo char(1) OUTPUT
	-- ,@mMVPid_movimiento char(2) OUTPUT
	 ,@mMVPds_movimiento varchar(60) OUTPUT
	-- ,@mMVPid_motivo char(2) OUTPUT
	-- ,@mMVPds_motivo varchar(60) OUTPUT
	,@mMVPfecha_movimiento datetime OUTPUT
	-- ,@mORGid_empresa char(4) OUTPUT
	-- ,@mORGds_empresa varchar(60) OUTPUT
	,@mORGid_zona char(1) OUTPUT
	,@mORGds_zona varchar(20) OUTPUT
	-- ,@mORGid_crp char(4) OUTPUT
	,@mORGcrp char(13) OUTPUT
	,@mORGds_crp varchar(60) OUTPUT
	,@mORGid_ambiente char(4) OUTPUT
	,@mORGds_ambiente varchar(100) OUTPUT
	,@mORGid_persona char(10) OUTPUT
	,@mORGds_persona varchar(80) OUTPUT
	,@mORGid_usuario varchar(15) OUTPUT
	,@mORGds_usuario varchar(100) OUTPUT
	-- ,@mORGid_sistelec char(6) OUTPUT
	-- ,@mORGds_sistelec varchar(25) OUTPUT
	-- ,@mORGid_set char(15) OUTPUT
	-- ,@mORGds_set varchar(30) OUTPUT
	-- ,@mORGid_alimentador char(15) OUTPUT
	-- ,@mORGds_alimentador varchar(15) OUTPUT
	-- ,@mORGid_sed char(15) OUTPUT
	-- ,@mORGds_sed varchar(15) OUTPUT
	-- ,@mORGid_circuito char(15) OUTPUT
	-- ,@mORGds_circuito varchar(15) OUTPUT
	-- ,@mORGposte_inicio char(15) OUTPUT
	-- ,@mORGds_poste_inicio varchar(15) OUTPUT
	-- ,@mORGposte_fin char(15) OUTPUT
	-- ,@mORGds_poste_fin varchar(15) OUTPUT
	-- ,@mORGlinea_at char(15) OUTPUT
	-- ,@mORGpunto_inicio char(15) OUTPUT
	-- ,@mORGpunto_fin char(15) OUTPUT
	-- ,@mORGid_activopadre int OUTPUT
	-- ,@mORGds_activopadre varchar(200) OUTPUT
	-- ,@mDSTid_empresa char(4) OUTPUT
	-- ,@mDSTds_empresa varchar(60) OUTPUT
	,@mDSTid_zona char(1) OUTPUT
	,@mDSTds_zona varchar(20) OUTPUT
	-- ,@mDSTid_crp char(4) OUTPUT
	,@mDSTcrp char(13) OUTPUT
	,@mDSTds_crp varchar(60) OUTPUT
	,@mDSTid_ambiente char(4) OUTPUT
	,@mDSTds_ambiente varchar(100) OUTPUT
	,@mDSTid_persona char(10) OUTPUT
	,@mDSTds_persona varchar(80) OUTPUT
	,@mDSTid_usuario char(15) OUTPUT
	,@mDSTds_usuario varchar(100) OUTPUT
	-- ,@mDSTid_sistelec char(6) OUTPUT
	-- ,@mDSTds_sistelec varchar(25) OUTPUT
	-- ,@mDSTid_set char(5) OUTPUT
	-- ,@mDSTds_set varchar(30) OUTPUT
	-- ,@mDSTid_alimentador char(15) OUTPUT
	-- ,@mDSTds_alimentador varchar(15) OUTPUT
	-- ,@mDSTid_sed char(15) OUTPUT
	-- ,@mDSTds_sed varchar(15) OUTPUT
	-- ,@mDSTid_circuito char(15) OUTPUT
	-- ,@mDSTds_circuito varchar(15) OUTPUT
	-- ,@mDSTposte_inicio char(15) OUTPUT
	-- ,@mDSTds_poste_inicio varchar(15) OUTPUT
	-- ,@mDSTposte_fin char(15) OUTPUT
	-- ,@mDSTds_poste_fin varchar(15) OUTPUT
	-- ,@mDSTlinea_at char(15) OUTPUT
	-- ,@mDSTpunto_inicio char(15) OUTPUT
	-- ,@mDSTpunto_fin char(15) OUTPUT
	-- ,@mDSTid_activopadre int OUTPUT
	-- ,@mDSTds_activopadre varchar(200) OUTPUT
	-- ,@mMVPobservaciones varchar(240) OUTPUT
	-- ,@mMVPdefinitivo char(1) OUTPUT
	-- ,@mMVPfecha_fin datetime OUTPUT
	-- ,@mMVPusuario_sistemas char(10) OUTPUT
	-- ,@mMVPaprueba_sistemas bit OUTPUT
	-- ,@mMVPfecha_sistemas datetime OUTPUT
	-- ,@mMVPusuario_patrimonio char(10) OUTPUT
	-- ,@mMVPaprueba_patrimonio bit OUTPUT
	-- ,@mMVPfecha_patrimonio datetime OUTPUT
	-- ,@mMVPretorno char(1) OUTPUT
	-- ,@mMVPusuario_retorno char(10) OUTPUT
	-- ,@mMVPfecha_retorno char(10) OUTPUT
	-- ,@mMVPusuario_registro char(10) OUTPUT
	-- ,@mMVPfecha_registro datetime OUTPUT
AS
-- inserts a new row into the table
INSERT [dbo].[acfCMVp_Cabecera_Movimiento]
(
  [MVPid_proceso]
 ,[MVPtipo]
-- ,[MVPid_movimiento]
 ,[MVPds_movimiento]
-- ,[MVPid_motivo]
-- ,[MVPds_motivo]
 ,[MVPfecha_movimiento]
-- ,[ORGid_empresa]
-- ,[ORGds_empresa]
 ,[ORGid_zona]
 ,[ORGds_zona]
-- ,[ORGid_crp]
 ,[ORGcrp]
 ,[ORGds_crp]
 ,[ORGid_ambiente]
 ,[ORGds_ambiente]
 ,[ORGid_persona]
 ,[ORGds_persona]
 ,[ORGid_usuario]
 ,[ORGds_usuario]
-- ,[ORGid_sistelec]
-- ,[ORGds_sistelec]
-- ,[ORGid_set]
-- ,[ORGds_set]
-- ,[ORGid_alimentador]
-- ,[ORGds_alimentador]
-- ,[ORGid_sed]
-- ,[ORGds_sed]
-- ,[ORGid_circuito]
-- ,[ORGds_circuito]
-- ,[ORGposte_inicio]
-- ,[ORGds_poste_inicio]
-- ,[ORGposte_fin]
-- ,[ORGds_poste_fin]
-- ,[ORGlinea_at]
-- ,[ORGpunto_inicio]
-- ,[ORGpunto_fin]
-- ,[ORGid_activopadre]
-- ,[ORGds_activopadre]
-- ,[DSTid_empresa]
-- ,[DSTds_empresa]
 ,[DSTid_zona]
 ,[DSTds_zona]
-- ,[DSTid_crp]
 ,[DSTcrp]
 ,[DSTds_crp]
 ,[DSTid_ambiente]
 ,[DSTds_ambiente]
 ,[DSTid_persona]
 ,[DSTds_persona]
 ,[DSTid_usuario]
 ,[DSTds_usuario]
-- ,[DSTid_sistelec]
-- ,[DSTds_sistelec]
-- ,[DSTid_set]
-- ,[DSTds_set]
-- ,[DSTid_alimentador]
-- ,[DSTds_alimentador]
-- ,[DSTid_sed]
-- ,[DSTds_sed]
-- ,[DSTid_circuito]
-- ,[DSTds_circuito]
-- ,[DSTposte_inicio]
-- ,[DSTds_poste_inicio]
-- ,[DSTposte_fin]
-- ,[DSTds_poste_fin]
-- ,[DSTlinea_at]
-- ,[DSTpunto_inicio]
-- ,[DSTpunto_fin]
-- ,[DSTid_activopadre]
-- ,[DSTds_activopadre]
-- ,[MVPobservaciones]
-- ,[MVPdefinitivo]
-- ,[MVPfecha_fin]
-- ,[MVPusuario_sistemas]
-- ,[MVPaprueba_sistemas]
-- ,[MVPfecha_sistemas]
-- ,[MVPusuario_patrimonio]
-- ,[MVPaprueba_patrimonio]
-- ,[MVPfecha_patrimonio]
-- ,[MVPretorno]
-- ,[MVPusuario_retorno]
-- ,[MVPfecha_retorno]
-- ,[MVPusuario_registro]
-- ,[MVPfecha_registro]
)
VALUES
(
 @iMVPid_proceso
 ,@mMVPtipo
-- ,@mMVPid_movimiento
 ,@mMVPds_movimiento
-- ,@mMVPid_motivo
-- ,@mMVPds_motivo
 ,@mMVPfecha_movimiento
-- ,@mORGid_empresa
-- ,@mORGds_empresa
 ,@mORGid_zona
 ,@mORGds_zona
-- ,@mORGid_crp
 ,@mORGcrp
 ,@mORGds_crp
 ,@mORGid_ambiente
 ,@mORGds_ambiente
 ,@mORGid_persona
 ,@mORGds_persona
 ,@mORGid_usuario
 ,@mORGds_usuario
-- ,@mORGid_sistelec
-- ,@mORGds_sistelec
-- ,@mORGid_set
-- ,@mORGds_set
-- ,@mORGid_alimentador
-- ,@mORGds_alimentador
-- ,@mORGid_sed
-- ,@mORGds_sed
-- ,@mORGid_circuito
-- ,@mORGds_circuito
-- ,@mORGposte_inicio
-- ,@mORGds_poste_inicio
-- ,@mORGposte_fin
-- ,@mORGds_poste_fin
-- ,@mORGlinea_at
-- ,@mORGpunto_inicio
-- ,@mORGpunto_fin
-- ,@mORGid_activopadre
-- ,@mORGds_activopadre
-- ,@mDSTid_empresa
-- ,@mDSTds_empresa
 ,@mDSTid_zona
 ,@mDSTds_zona
-- ,@mDSTid_crp
 ,@mDSTcrp
 ,@mDSTds_crp
 ,@mDSTid_ambiente
 ,@mDSTds_ambiente
 ,@mDSTid_persona
 ,@mDSTds_persona
 ,@mDSTid_usuario
 ,@mDSTds_usuario
-- ,@mDSTid_sistelec
-- ,@mDSTds_sistelec
-- ,@mDSTid_set
-- ,@mDSTds_set
-- ,@mDSTid_alimentador
-- ,@mDSTds_alimentador
-- ,@mDSTid_sed
-- ,@mDSTds_sed
-- ,@mDSTid_circuito
-- ,@mDSTds_circuito
-- ,@mDSTposte_inicio
-- ,@mDSTds_poste_inicio
-- ,@mDSTposte_fin
-- ,@mDSTds_poste_fin
-- ,@mDSTlinea_at
-- ,@mDSTpunto_inicio
-- ,@mDSTpunto_fin
-- ,@mDSTid_activopadre
-- ,@mDSTds_activopadre
-- ,@mMVPobservaciones
-- ,@mMVPdefinitivo
-- ,@mMVPfecha_fin
-- ,@mMVPusuario_sistemas
-- ,@mMVPaprueba_sistemas
-- ,@mMVPfecha_sistemas
-- ,@mMVPusuario_patrimonio
-- ,@mMVPaprueba_patrimonio
-- ,@mMVPfecha_patrimonio
-- ,@mMVPretorno
-- ,@mMVPusuario_retorno
-- ,@mMVPfecha_retorno
-- ,@mMVPusuario_registro
-- ,@mMVPfecha_registro
)
SELECT 
  @iMVPid_proceso = [MVPid_proceso]
 ,@mMVPtipo = [MVPtipo]
-- ,@mMVPid_movimiento = [MVPid_movimiento]
 ,@mMVPds_movimiento = [MVPds_movimiento]
-- ,@mMVPid_motivo = [MVPid_motivo]
-- ,@mMVPds_motivo = [MVPds_motivo]
 ,@mMVPfecha_movimiento = [MVPfecha_movimiento]
-- ,@mORGid_empresa = [ORGid_empresa]
-- ,@mORGds_empresa = [ORGds_empresa]
 ,@mORGid_zona = [ORGid_zona]
 ,@mORGds_zona = [ORGds_zona]
-- ,@mORGid_crp = [ORGid_crp]
 ,@mORGcrp = [ORGcrp]
 ,@mORGds_crp = [ORGds_crp]
 ,@mORGid_ambiente = [ORGid_ambiente]
 ,@mORGds_ambiente = [ORGds_ambiente]
 ,@mORGid_persona = [ORGid_persona]
 ,@mORGds_persona = [ORGds_persona]
 ,@mORGid_usuario = [ORGid_usuario]
 ,@mORGds_usuario = [ORGds_usuario]
-- ,@mORGid_sistelec = [ORGid_sistelec]
-- ,@mORGds_sistelec = [ORGds_sistelec]
-- ,@mORGid_set = [ORGid_set]
-- ,@mORGds_set = [ORGds_set]
-- ,@mORGid_alimentador = [ORGid_alimentador]
-- ,@mORGds_alimentador = [ORGds_alimentador]
-- ,@mORGid_sed = [ORGid_sed]
-- ,@mORGds_sed = [ORGds_sed]
-- ,@mORGid_circuito = [ORGid_circuito]
-- ,@mORGds_circuito = [ORGds_circuito]
-- ,@mORGposte_inicio = [ORGposte_inicio]
-- ,@mORGds_poste_inicio = [ORGds_poste_inicio]
-- ,@mORGposte_fin = [ORGposte_fin]
-- ,@mORGds_poste_fin = [ORGds_poste_fin]
-- ,@mORGlinea_at = [ORGlinea_at]
-- ,@mORGpunto_inicio = [ORGpunto_inicio]
-- ,@mORGpunto_fin = [ORGpunto_fin]
-- ,@mORGid_activopadre = [ORGid_activopadre]
-- ,@mORGds_activopadre = [ORGds_activopadre]
-- ,@mDSTid_empresa = [DSTid_empresa]
-- ,@mDSTds_empresa = [DSTds_empresa]
 ,@mDSTid_zona = [DSTid_zona]
 ,@mDSTds_zona = [DSTds_zona]
-- ,@mDSTid_crp = [DSTid_crp]
 ,@mDSTcrp = [DSTcrp]
 ,@mDSTds_crp = [DSTds_crp]
 ,@mDSTid_ambiente = [DSTid_ambiente]
 ,@mDSTds_ambiente = [DSTds_ambiente]
 ,@mDSTid_persona = [DSTid_persona]
 ,@mDSTds_persona = [DSTds_persona]
 ,@mDSTid_usuario = [DSTid_usuario]
 ,@mDSTds_usuario = [DSTds_usuario]
-- ,@mDSTid_sistelec = [DSTid_sistelec]
-- ,@mDSTds_sistelec = [DSTds_sistelec]
-- ,@mDSTid_set = [DSTid_set]
-- ,@mDSTds_set = [DSTds_set]
-- ,@mDSTid_alimentador = [DSTid_alimentador]
-- ,@mDSTds_alimentador = [DSTds_alimentador]
-- ,@mDSTid_sed = [DSTid_sed]
-- ,@mDSTds_sed = [DSTds_sed]
-- ,@mDSTid_circuito = [DSTid_circuito]
-- ,@mDSTds_circuito = [DSTds_circuito]
-- ,@mDSTposte_inicio = [DSTposte_inicio]
-- ,@mDSTds_poste_inicio = [DSTds_poste_inicio]
-- ,@mDSTposte_fin = [DSTposte_fin]
-- ,@mDSTds_poste_fin = [DSTds_poste_fin]
-- ,@mDSTlinea_at = [DSTlinea_at]
-- ,@mDSTpunto_inicio = [DSTpunto_inicio]
-- ,@mDSTpunto_fin = [DSTpunto_fin]
-- ,@mDSTid_activopadre = [DSTid_activopadre]
-- ,@mDSTds_activopadre = [DSTds_activopadre]
-- ,@mMVPobservaciones = [MVPobservaciones]
-- ,@mMVPdefinitivo = [MVPdefinitivo]
-- ,@mMVPfecha_fin = [MVPfecha_fin]
-- ,@mMVPusuario_sistemas = [MVPusuario_sistemas]
-- ,@mMVPaprueba_sistemas = [MVPaprueba_sistemas]
-- ,@mMVPfecha_sistemas = [MVPfecha_sistemas]
-- ,@mMVPusuario_patrimonio = [MVPusuario_patrimonio]
-- ,@mMVPaprueba_patrimonio = [MVPaprueba_patrimonio]
-- ,@mMVPfecha_patrimonio = [MVPfecha_patrimonio]
-- ,@mMVPretorno = [MVPretorno]
-- ,@mMVPusuario_retorno = [MVPusuario_retorno]
-- ,@mMVPfecha_retorno = [MVPfecha_retorno]
-- ,@mMVPusuario_registro = [MVPusuario_registro]
-- ,@mMVPfecha_registro = [MVPfecha_registro]
FROM [dbo].[acfCMVp_Cabecera_Movimiento]
WHERE 
[MVPid_proceso] = @iMVPid_proceso
END























-- Delete a row based on the primary key(s)
------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 22/03/2017 10:50:32 
------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_D_acfCMVp_Cabecera_Movimiento]
@iMVPid_proceso int
AS
-- delete all matching from the table
DELETE [dbo].[acfCMVp_Cabecera_Movimiento]
WHERE 
[MVPid_proceso] = @iMVPid_proceso
END


















-- Select one row based on the primary key(s)
------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 22/03/2017 10:50:32 
------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_B_acfCMVp_Cabecera_Movimiento]
@iMVPid_proceso int
AS
-- selects all rows from the table
SELECT 
 [MVPid_proceso]
 ,[MVPtipo]
-- ,[MVPid_movimiento]
 ,[MVPds_movimiento]
-- ,[MVPid_motivo]
-- ,[MVPds_motivo]
 ,[MVPfecha_movimiento]
-- ,[ORGid_empresa]
-- ,[ORGds_empresa]
 ,[ORGid_zona]
 ,[ORGds_zona]
-- ,[ORGid_crp]
 ,[ORGcrp]
 ,[ORGds_crp]
 ,[ORGid_ambiente]
 ,[ORGds_ambiente]
 ,[ORGid_persona]
 ,[ORGds_persona]
 ,[ORGid_usuario]
 ,[ORGds_usuario]
-- ,[ORGid_sistelec]
-- ,[ORGds_sistelec]
-- ,[ORGid_set]
-- ,[ORGds_set]
-- ,[ORGid_alimentador]
-- ,[ORGds_alimentador]
-- ,[ORGid_sed]
-- ,[ORGds_sed]
-- ,[ORGid_circuito]
-- ,[ORGds_circuito]
-- ,[ORGposte_inicio]
-- ,[ORGds_poste_inicio]
-- ,[ORGposte_fin]
-- ,[ORGds_poste_fin]
-- ,[ORGlinea_at]
-- ,[ORGpunto_inicio]
-- ,[ORGpunto_fin]
-- ,[ORGid_activopadre]
-- ,[ORGds_activopadre]
-- ,[DSTid_empresa]
-- ,[DSTds_empresa]
 ,[DSTid_zona]
 ,[DSTds_zona]
-- ,[DSTid_crp]
 ,[DSTcrp]
 ,[DSTds_crp]
 ,[DSTid_ambiente]
 ,[DSTds_ambiente]
 ,[DSTid_persona]
 ,[DSTds_persona]
 ,[DSTid_usuario]
 ,[DSTds_usuario]
-- ,[DSTid_sistelec]
-- ,[DSTds_sistelec]
-- ,[DSTid_set]
-- ,[DSTds_set]
-- ,[DSTid_alimentador]
-- ,[DSTds_alimentador]
-- ,[DSTid_sed]
-- ,[DSTds_sed]
-- ,[DSTid_circuito]
-- ,[DSTds_circuito]
-- ,[DSTposte_inicio]
-- ,[DSTds_poste_inicio]
-- ,[DSTposte_fin]
-- ,[DSTds_poste_fin]
-- ,[DSTlinea_at]
-- ,[DSTpunto_inicio]
-- ,[DSTpunto_fin]
-- ,[DSTid_activopadre]
-- ,[DSTds_activopadre]
-- ,[MVPobservaciones]
-- ,[MVPdefinitivo]
-- ,[MVPfecha_fin]
-- ,[MVPusuario_sistemas]
-- ,[MVPaprueba_sistemas]
-- ,[MVPfecha_sistemas]
-- ,[MVPusuario_patrimonio]
-- ,[MVPaprueba_patrimonio]
-- ,[MVPfecha_patrimonio]
-- ,[MVPretorno]
-- ,[MVPusuario_retorno]
-- ,[MVPfecha_retorno]
-- ,[MVPusuario_registro]
-- ,[MVPfecha_registro]
FROM [dbo].[acfCMVp_Cabecera_Movimiento]
WHERE 
[MVPid_proceso] = @iMVPid_proceso
END


